### ISSUE TITLE
Ignore timezone

### ISSUE THREAD

**Issue by ghost** [JackStouffer/date-parser#1]
I'd like to ignore timezone with this code

assert(parse("Sat, 12 Mar 2016 01:30:59 -0900", null, /\* ignoreTimezone */ true) == SysTime(DateTime(2016, 3, 12, 01, 30, 59)));

but I got the output

core.exception.RangeError@../../.dub/packages/dateparser-master/src/dateparser.d(1142): Range violation

**Comment by JackStouffer** [comment]
Try using master if you are on `0.0.2`

**Comment by ghost** [comment]
I'm using "~master"

**Comment by JackStouffer** [comment]
Have you used `dub upgrade`

**Comment by ghost** [comment]
I did.

**Comment by JackStouffer** [comment]
This actually happens with or without the extra arguments. Investigating now.

**Comment by JackStouffer** [comment]
Fixed in 2af6c6b
