### ISSUE TITLE
Unknown string format for "Thu Nov 07 2019 17:00:00 GMT+0000 (UTC)"

### ISSUE THREAD

**Issue by WebFreak001** [JackStouffer/date-parser#27]
This is the default string format javascript applications output which some servers actually use for serving to their frontend...

Would be great to have this supported. Examples:

```
Thu Nov 07 2019 17:00:00 GMT+0000 (UTC)
Mon Dec 09 2019 16:26:16 GMT+0100 (Central European Standard Time)
```

Removing the extra comment (UTC) or (Central European Standard Time) at the end seems to be enough to fix this but this might actually be useful if this was already done from inside the library.

For now I'm using a custom parse function which pre-processes the string:
```d
auto parseDate(const(char)[] s)
{
	import dateparser : parseDateRaw = parse;

	if (s.endsWith(")"))
    {
    	auto end = s.lastIndexOf('(');
		if (end != -1)
        	s = s[0 .. end].strip;
        return parseDateRaw(s);
	}
    else
    	return parseDateRaw(s);
}
```

**Comment by JackStouffer** [comment]
@WebFreak001 The reason the code gets confused is that it sees two different timezones in the string. From it's perspective, you're asking for a date which is in both the `GMT+0100` timezone and in the `Central European Standard Time` timezone.

This format is a really odd corner case, so your best option (if you can't change your inputs to something else) is to turn on fuzzy matching and then rely on the GMT auto-timezone parsing. So it would be 

```d
parse(
    "Thu Nov 07 2019 17:00:00 GMT-0100 (UTC)",
    No.ignoreTimezone,
    null,
    No.dayFirst,
    No.yearFirst,
    Yes.fuzzy
);
```

which gives you the correct result.

**Comment by WebFreak001** [comment]
uh where did you get the `GMT-0100 (UTC)` from? I was only talking about matching timezone & offset names which seem to be generated from some kind of library in the wild, which I found when parsing some RSS feeds.

**Comment by JackStouffer** [comment]
Sorry, it was from a test I was writing. But the point remains. With the string

```
Thu Nov 07 2019 17:00:00 GMT+0000 (UTC)
```

The code doesn't hardcode the name of timezones other than GMT, so it sees two timezones defined at once: `GMT+0000` and `UTC`.

**Comment by WebFreak001** [comment]
I believe the stuff in `()` is just a comment which should be ignored by parsing apps, but I don't know in which standard that is specified. At least that's how the JS Date API works

**Comment by JackStouffer** [comment]
Looks like this is the standard output of the JavaScript `Date.toString` method. 

From this library's perspective, I don't think I can assume that any text inside of a `()` should act as a comment. I can easily imagine some weird date format like the following

```
Jan 3, 2020  8:30 AM (EST)
```

where stuff inside of the parentheses is relevant to the result.

I'm going to close this and suggest that you turn on fuzzy matching, which is designed to handle formats like this. If this does not give the correct result please let me know.
